apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: argocd
  
  source:
    helm:
      version: v3
      valueFiles:
      - values.yaml
    path: helm-charts
    repoURL: https://github.com/paas2/argo-deploy-secret
    targetRevision: HEAD
  syncPolicy:
    # syncOptions:
    # - CreateNamespace=true   
    automated:  
      prune: true             